# Generated by Django 2.1.1 on 2019-07-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.TextField()),
                ('nickname', models.TextField()),
                ('headimg', models.TextField()),
                ('authprovider', models.IntegerField(choices=[(0, 'Alipay'), (1, 'Weixin')])),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='cache_suspend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Login'), (1, 'Token')])),
                ('key', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='domain_to_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField()),
                ('url', models.TextField()),
                ('key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='file_key_to_path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('path', models.TextField()),
                ('resource_key', models.TextField()),
                ('reference', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='hash_to_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField(unique=True)),
                ('key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_customed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_iframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('value', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_info',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('brief', models.TextField()),
                ('headimg', models.TextField()),
                ('userid', models.IntegerField()),
                ('created', models.IntegerField()),
                ('modified', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('readable', models.IntegerField(choices=[(0, 'Every one'), (3, 'Logged only'), (1, 'Owner only'), (2, 'Token'), (4, 'Logged or token')], default=0)),
                ('writeable', models.IntegerField(choices=[(0, 'Every one'), (3, 'Logged only'), (1, 'Owner only'), (2, 'Token'), (4, 'Logged or token')], default=1)),
                ('modifiable', models.IntegerField(choices=[(0, 'Every one'), (3, 'Logged only'), (1, 'Owner only'), (2, 'Token'), (4, 'Logged or token')], default=1)),
                ('permitteduser', models.IntegerField()),
                ('token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_restful',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('volume', models.IntegerField(default=-1)),
                ('capability', models.IntegerField(default=-1)),
                ('readable', models.IntegerField(choices=[(0, 'Every one'), (3, 'Logged only'), (1, 'Owner only'), (2, 'Token'), (4, 'Logged or token')], default=0)),
                ('writeable', models.IntegerField(choices=[(0, 'Every one'), (3, 'Logged only'), (1, 'Owner only'), (2, 'Token'), (4, 'Logged or token')], default=1)),
                ('modifiable', models.IntegerField(choices=[(0, 'Every one'), (3, 'Logged only'), (1, 'Owner only'), (2, 'Token'), (4, 'Logged or token')], default=1)),
                ('token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_restful_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('item', models.TextField()),
                ('value', models.TextField()),
                ('readable', models.IntegerField(choices=[(0, 'Every one'), (3, 'Logged only'), (1, 'Owner only'), (2, 'Token'), (4, 'Logged or token')], default=0)),
                ('writeable', models.IntegerField(choices=[(0, 'Every one'), (3, 'Logged only'), (1, 'Owner only'), (2, 'Token'), (4, 'Logged or token')], default=1)),
                ('modifiable', models.IntegerField(choices=[(0, 'Every one'), (3, 'Logged only'), (1, 'Owner only'), (2, 'Token'), (4, 'Logged or token')], default=1)),
                ('token', models.TextField()),
                ('owner', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('state', models.IntegerField(choices=[(0, 'Play'), (1, 'Pause'), (2, 'Stop'), (3, 'Prepare to delete')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='resource_templated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('source', models.TextField()),
                ('api', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_to_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('user', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Customed'), (2, 'Templated'), (3, 'Restful API'), (4, 'Short Link'), (5, 'iFrame')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('default', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'customed'), (2, 'templated'), (3, 'api'), (5, 'iframe'), (4, 'link')], default=1)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
