# Generated by Django 2.2.4 on 2019-08-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='domain_to_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(unique=True)),
                ('user', models.IntegerField(default=-1)),
                ('token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='file_hash_to_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField(unique=True)),
                ('key', models.TextField()),
                ('reference', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='file_key_to_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='resource_pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('path', models.TextField()),
                ('title', models.TextField()),
                ('msg', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='hash_to_key',
        ),
        migrations.RemoveField(
            model_name='resource_info',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='resource_to_user',
            name='user',
        ),
        migrations.AddField(
            model_name='resource_to_user',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auth_user',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
